language: go
sudo: false
go:
- "1.10.x"
install:
  - go get -v -t github.com/golang/lint/golint honnef.co/go/tools/cmd/megacheck
  - go get -t ./...
before_script:
  # - go vet ./...
script:
 - ./scripts/presubmit.sh
